package tms;

import javax.swing.JOptionPane;

/**
 *
 * @author Chris Liebert
 */
public class CreateTaskDialog extends javax.swing.JDialog {

    // application object
    TMSGUI tms;

    /**
     * Creates new form CreateTaskDialog
     *
     * @param _tms a reference to the running application object
     * @param modal
     */
    public CreateTaskDialog(TMSGUI _tms, boolean modal) {
        super(_tms.frame, modal);
        tms = _tms;
        initComponents();
        setLocationByPlatform(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();
        CreateTaskButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldKeyPressed(evt);
            }
        });

        CreateTaskButton.setText("Create Task");
        CreateTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateTaskButtonActionPerformed(evt);
            }
        });
        CreateTaskButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CreateTaskButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreateTaskButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateTaskButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateTaskButtonActionPerformed
        // The create task button was pressed.
        // Try to create the task
        try {
            tms.taskController.createTask(textField.getText());
            tms.panel.toDoList.updateUI();
        } catch (Exception e) {
            // Show error dialog
            JOptionPane.showMessageDialog(tms.frame,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        // Clear the text field for future task creations
        textField.setText("");
        // Hide the dialog
        setVisible(false);
    }//GEN-LAST:event_CreateTaskButtonActionPerformed

    private void textFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldKeyPressed
        if(evt.getKeyCode() == 10) {
            CreateTaskButtonActionPerformed(null);
        }
    }//GEN-LAST:event_textFieldKeyPressed

    private void CreateTaskButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CreateTaskButtonKeyPressed
        if(evt.getKeyCode() == 10) {
            CreateTaskButtonActionPerformed(null);
        }
    }//GEN-LAST:event_CreateTaskButtonKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateTaskButton;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
